In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
import math
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.svm import LinearSVC
import pickle

In [6]:
file_path = '/content/train.dat'
data = np.loadtxt(file_path)

In [7]:
first_five_datapoints = data[:5, :]
print("First 5 datapoints:")
print(first_five_datapoints)

First 5 datapoints:
[[1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1.
  1. 1. 0. 0. 1. 0. 1. 1. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.
  1. 1. 0. 1. 0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1.
  0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0.
  1. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1.
  0. 1. 0. 0. 1. 1. 1. 0. 0.]]


In [8]:
def preprocess_data( data ):
    X_raw = data[:,:-1]
    y_raw = data[:,-1]
    d = np.array([(1-2*ci) for ci in X_raw ])
    X=[]
    for i in range(d.shape[0]):
      temp = []
      for j in range(32):
        x=1
        for k in range(32):
          if(k+j==32):
            break
          x=x*d[i][k+j]
        temp.append(x)
      X.append(temp)

    y = np.where( y_raw > 0, 1, -1 )
    X = np.array(X)
    new_columns = []
    new_columns.append(X)

    for i in range(32):
      for j in range(i+1,32):
        prod_col = np.multiply(X[:, i], X[:, j])
        new_columns.append(prod_col[:, np.newaxis])


    X_new = np.concatenate(new_columns, axis=1)
    return X_new,y


In [9]:
X, y = preprocess_data(data)

In [10]:
for i in range(1):
    print(f"Data Point {i} - X: {X[i, :]}, y: {y[i]}")

Data Point 0 - X: [-1.  1.  1.  1. -1. -1. -1.  1.  1.  1.  1.  1. -1.  1.  1. -1. -1. -1.
  1. -1.  1.  1.  1.  1. -1.  1. -1. -1. -1.  1.  1. -1. -1. -1. -1.  1.
  1.  1. -1. -1. -1. -1. -1.  1. -1. -1.  1.  1.  1. -1.  1. -1. -1. -1.
 -1.  1. -1.  1.  1.  1. -1. -1.  1.  1.  1. -1. -1. -1.  1.  1.  1.  1.
  1. -1.  1.  1. -1. -1. -1.  1. -1.  1.  1.  1.  1. -1.  1. -1. -1. -1.
  1.  1. -1.  1. -1. -1. -1.  1.  1.  1.  1.  1. -1.  1.  1. -1. -1. -1.
  1. -1.  1.  1.  1.  1. -1.  1. -1. -1. -1.  1.  1. -1. -1. -1. -1.  1.
  1.  1.  1.  1. -1.  1.  1. -1. -1. -1.  1. -1.  1.  1.  1.  1. -1.  1.
 -1. -1. -1.  1.  1. -1.  1.  1. -1. -1. -1. -1. -1.  1. -1. -1.  1.  1.
  1. -1.  1. -1. -1. -1. -1.  1. -1.  1.  1.  1. -1. -1.  1.  1. -1. -1.
 -1. -1. -1.  1. -1. -1.  1.  1.  1. -1.  1. -1. -1. -1. -1.  1. -1.  1.
  1.  1. -1. -1.  1. -1. -1. -1. -1. -1.  1. -1. -1.  1.  1.  1. -1.  1.
 -1. -1. -1. -1.  1. -1.  1.  1.  1. -1. -1.  1.  1.  1.  1.  1. -1.  1.
  1. -1. -1. -1.  1. -1.  1.  1. 

# Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(penalty='l2',solver='saga',random_state=0)
classifier.fit(X,y)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(random_state=0, solver='saga')

In [12]:
classifier.predict([X[0, :]])

array([-1])

In [13]:
file_path_2 = '/content/test.dat'
test_data = np.loadtxt(file_path_2)

In [14]:
X_test, y_test = preprocess_data(test_data)

In [15]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 1  1]
 [-1 -1]
 [-1 -1]
 ...
 [-1 -1]
 [-1 -1]
 [ 1  1]]


In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4994   60]
 [  37 4909]]


0.9903

2)Accuracy= 98.71 for C=0.1;
Accuracy= 99.07 for C=1;
Accuracy= 99.22 for C=10



3)Accuracy= 99.07 for tol=1e-4; Accuracy= 99.07 for tol=1e-4; Accuracy= 99.07 for tol=1e-2 i.e no change in accuracy after changing tol form low to high

4) Accuracy=99.06 for penalty=l2; Accuracy=99.06 for penalty=l1 i.e no change in accuracy

# Linear SVC

In [19]:
# cls = LinearSVC(loss="hinge")
# cls.fit(X,y)
cls = LinearSVC(penalty='l1',loss="squared_hinge",dual=False)
cls.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(dual=False, penalty='l1')

In [20]:
cls.score(X_test,y_test)

0.991

1)Accuracy changes from 98.85 to 99.14 after changing the loss in SVC from hinge to squared hinge


2)Accuracy=98.99 for C=0.1;Accuracy=99.13 for C=1;Accuracy=99.03 for C=10;

3)Accuracy= 99.07 for tol=1e-4; Accuracy= 99.18 for tol=1e-3; Accuracy= 99.14 for tol=1e-2

4)Accuracy=99.10 for penalty=l2;Accuracy=99.12 for penalty=l1